### ISSUE TITLE
random noise instead of trajectories with pretrained model on nuplan CL NR

### ISSUE THREAD

**Issue by NikitaSemenov** [Tsinghua-MARS-Lab/StateTransformer#154]
Could you explain please, how to use pretrained model to reproduce your result and visualizations on nuplan CL NR

**Comment by larksq** [comment]
Hi, thank you for your interest.

This might be somehow complicated at the time due to constantly changing codes and libraries (like the Transformers). We will reorganize the simulation codes after a conference acceptance.

For now, you can only reproduce the CL-NR results with the nuPlan garage simulations. Make sure to load the pre-trained model by revising the model name from 'scratch' to 'pretrain' if you have random noise. 

Official support will come in the next months. Stay tuned.
